///////////////////////////////////////////////////////////
//  Adapter.cs
//  Implementation of the Class Adapter
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 11:56:26 AM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ZivotinjskoCarstvo;
namespace ZivotinjskoCarstvo {
	public class Adapter : IZivotinjskaAktivnost {

		public ZivotinjskoCarstvo.Ptice m_Ptice;

		public Adapter(Ptice p){

			m_Ptice = p;
		}

		~Adapter(){

		}

		public void OglasiSe()
		{

			m_Ptice.Pevaj();

			
		}

		public void PomeriSe(){

			m_Ptice.Leti();

		}

	}//end Adapter

}//end namespace ZivotinjskoCarstvo