///////////////////////////////////////////////////////////
//  IZivotinjskaAktivnost.cs
//  Implementation of the Interface IZivotinjskaAktivnost
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 11:56:26 AM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ZivotinjskoCarstvo {
	public interface IZivotinjskaAktivnost  {

		
		
	   void OglasiSe();

		void PomeriSe();

	}//end IZivotinjskaAktivnost

}//end namespace ZivotinjskoCarstvo