///////////////////////////////////////////////////////////
//  Konj.cs
//  Implementation of the Class Konj
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 11:56:26 AM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ZivotinjskoCarstvo;
namespace ZivotinjskoCarstvo {
	public class Konj : IZivotinjskaAktivnost {

		public Konj(){}

		~Konj(){}

		public void OglasiSe()
		{
			Console.WriteLine("Konj");
		}

		public void PomeriSe()
		{
			Console.WriteLine("Konj");
		}
	}//end Konj

}//end namespace ZivotinjskoCarstvo