///////////////////////////////////////////////////////////
//  Ptice.cs
//  Implementation of the Class Ptice
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 11:56:26 AM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ZivotinjskoCarstvo {
	public abstract class Ptice {

		public Ptice(){

		}

		~Ptice(){

		}

		public abstract void Leti();

		public abstract void Pevaj();

	}//end Ptice

}//end namespace ZivotinjskoCarstvo