///////////////////////////////////////////////////////////
//  Svinja.cs
//  Implementation of the Class Svinja
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 12:10:24 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ZivotinjskoCarstvo;
namespace ZivotinjskoCarstvo {
	public class Svinja : IZivotinjskaAktivnost {

		public Svinja(){

		}

		~Svinja(){

		}

		public void OglasiSe(){
			Console.WriteLine("Svinja grkoce");
		}

		public void PomeriSe(){
			Console.WriteLine("Svinja trci po dvoristu");
		}

	}//end Svinja

}//end namespace ZivotinjskoCarstvo