///////////////////////////////////////////////////////////
//  Vrabac.cs
//  Implementation of the Class Vrabac
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2020 11:56:26 AM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ZivotinjskoCarstvo;
namespace ZivotinjskoCarstvo {
	public class Vrabac : Ptice {

		public Vrabac(){

		}

		~Vrabac(){

		}

		public override void Leti()
		{
			Console.WriteLine("Vrabac leti"); 
		}

		public override void Pevaj()
		{
			Console.WriteLine("Vrabac crvkuce");
		}
	}//end Vrabac

}//end namespace ZivotinjskoCarstvo